debug:7771
debug:7771
debug:./face_results/image9.jpg
Traceback (most recent call last):
  File "./face.py", line 50, in <module>
    f_record.send(len(b).to_bytes())
TypeError: to_bytes() missing required argument 'length' (pos 1)
